version: '3.3'

services:    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.1
        restart: always
        environment:
           PMA_HOST: db
        ports:
          - "8080:80"

    rabbitmq:
        image: "rabbitmq:3-management"
        hostname: "localhost"
        ports:
        - "15672:15672"
        - "5672:5672"
        volumes:
        - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
        depends_on:
        - db
        
        

    node-app:
        build: .
        environment:
            - DATABASE_HOST=db
            - TZ=Europe/Sarajevo
        depends_on:
            - db
            - rabbitmq
        restart: always
        ports:
            - 8000:8000
        links:
            - rabbitmq
            - db

 
    db:
        build: ./db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        cap_add:
            - SYS_NICE 
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: url-db